// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PiecesOfArt_Application_Assignment.Data;

#nullable disable

namespace PiecesOfArt_Application_Assignment.Migrations
{
    [DbContext(typeof(ApplicatioDbContext))]
    [Migration("20241025210336_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PiecesOfArt_Application_Assignment.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A 19th-century art movement characterized by small, thin brush strokes and emphasis on light and movement.",
                            Name = "Impressionism"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A period in European history marking the revival of classical learning and wisdom.",
                            Name = "Renaissance"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Art that uses shapes, colors, forms, and gestural marks to achieve its effect rather than depicting objects.",
                            Name = "Abstract"
                        },
                        new
                        {
                            Id = 4,
                            Description = "A broad category that reflects artistic work produced during the late 19th to mid-20th century.",
                            Name = "Modern"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Art from ancient civilizations, including Egyptian, Mesopotamian, and classical Greek.",
                            Name = "Ancient"
                        });
                });

            modelBuilder.Entity("PiecesOfArt_Application_Assignment.Models.LoyaltyCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("loyaltyCards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "10% Off",
                            Name = "Bronze"
                        },
                        new
                        {
                            Id = 2,
                            Description = "20% Off",
                            Name = "Silver"
                        },
                        new
                        {
                            Id = 3,
                            Description = "30% Off",
                            Name = "Gold"
                        },
                        new
                        {
                            Id = 4,
                            Description = "40% Off",
                            Name = "Platinum"
                        },
                        new
                        {
                            Id = 5,
                            Description = "50% Off",
                            Name = "Crystal"
                        });
                });

            modelBuilder.Entity("PiecesOfArt_Application_Assignment.Models.PieceOfArt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<DateOnly>("PublicatioDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("pieceOfArts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Price = 100000.0,
                            PublicatioDate = new DateOnly(1889, 6, 1),
                            Title = "Starry Night",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Price = 500000.0,
                            PublicatioDate = new DateOnly(1503, 10, 1),
                            Title = "The Mona Lisa",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Price = 120000.0,
                            PublicatioDate = new DateOnly(1923, 7, 1),
                            Title = "Composition VIII",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Price = 200000.0,
                            PublicatioDate = new DateOnly(1931, 5, 1),
                            Title = "The Persistence of Memory",
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            Price = 150000.0,
                            PublicatioDate = new DateOnly(1400, 1, 1),
                            Title = "Small Pyramid",
                            UserId = 5
                        });
                });

            modelBuilder.Entity("PiecesOfArt_Application_Assignment.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoyaltyCardId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LoyaltyCardId");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 30,
                            Email = "john@example.com",
                            LoyaltyCardId = 1,
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = 2,
                            Age = 28,
                            Email = "jane@example.com",
                            LoyaltyCardId = 2,
                            Name = "Jane Smith"
                        },
                        new
                        {
                            Id = 3,
                            Age = 35,
                            Email = "emily@example.com",
                            LoyaltyCardId = 3,
                            Name = "Emily Johnson"
                        },
                        new
                        {
                            Id = 4,
                            Age = 40,
                            Email = "michael@example.com",
                            LoyaltyCardId = 4,
                            Name = "Michael Brown"
                        },
                        new
                        {
                            Id = 5,
                            Age = 25,
                            Email = "david@example.com",
                            LoyaltyCardId = 5,
                            Name = "David Williams"
                        });
                });

            modelBuilder.Entity("PiecesOfArt_Application_Assignment.Models.PieceOfArt", b =>
                {
                    b.HasOne("PiecesOfArt_Application_Assignment.Models.Category", "Category")
                        .WithMany("pieceOfArts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PiecesOfArt_Application_Assignment.Models.User", "User")
                        .WithMany("pieceOfArts")
                        .HasForeignKey("UserId");

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PiecesOfArt_Application_Assignment.Models.User", b =>
                {
                    b.HasOne("PiecesOfArt_Application_Assignment.Models.LoyaltyCard", "LoyaltyCard")
                        .WithMany("Users")
                        .HasForeignKey("LoyaltyCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoyaltyCard");
                });

            modelBuilder.Entity("PiecesOfArt_Application_Assignment.Models.Category", b =>
                {
                    b.Navigation("pieceOfArts");
                });

            modelBuilder.Entity("PiecesOfArt_Application_Assignment.Models.LoyaltyCard", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("PiecesOfArt_Application_Assignment.Models.User", b =>
                {
                    b.Navigation("pieceOfArts");
                });
#pragma warning restore 612, 618
        }
    }
}
